spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/document_flow
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver

minio:
  url: http://localhost:9001
  access-key: minioadmin
  secret-key: minioadmin123
  bucket: documents